run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - revive
    - gocyclo
    - gocritic
    - bodyclose
    - dogsled
    - dupl
    - exportloopref
    - goconst
    - gocognit
    - gosec
    - misspell
    - prealloc
    - stylecheck
    - unconvert
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 15
  govet:
    check-shadowing: true
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gocognit
        - dupl
