name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'  

      - name: Install protoc and plugins
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Check proto file exists
        run: |
          ls -la api/proto/aggregator/v1/aggregator.proto
          head -10 api/proto/aggregator/v1/aggregator.proto

      - name: Generate protobuf code
        run: |
          mkdir -p gen/go
          protoc \
            --proto_path=api/proto \
            --go_out=paths=source_relative:gen/go \
            --go-grpc_out=paths=source_relative:gen/go \
            api/proto/aggregator/v1/aggregator.proto
          ls -la gen/go/aggregator/v1

      - name: Run go mod tidy
        run: go mod tidy

      - name: Run linter
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.2
          golangci-lint run ./...

      - name: Build project
        run: go build ./...

      - name: Run tests
        run: go test ./...
