name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.5'

    - name: Install protoc compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Install protoc-gen-go and protoc-gen-go-grpc plugins
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.31.0
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0
        echo "$HOME/go/bin" >> $GITHUB_PATH

    - name: Generate protobuf code
      run: |
        pwd  # Для отладки: показывает текущую директорию
        ls -la  # Для отладки: показывает содержимое корня
        mkdir -p gen/go  # Создаёт директорию gen/go/, если её нет
        protoc \
          --proto_path=api/proto \
          --go_out=gen/go \
          --go-grpc_out=gen/go \
          api/proto/aggregator/v1/aggregator.proto

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.64.2
        echo "$GOPATH/bin" >> $GITHUB_PATH

    - name: Run linter
      run: golangci-lint run ./...

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...
